[package]
name = "wp-app"
description = "The windowed application"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "word-processor"
path = "src/main.rs"

[dependencies]
wp-docx = { path = "../wp-docx" }
wp-segment = { path = "../wp-segment" }
wp-layout = { path = "../wp-layout" }
wp-pdf = { path = "../wp-pdf" }
wp-raster = { path = "../wp-raster" }
wp-image = { path = "../wp-image" }
wp-svg = { path = "../wp-svg" }
wp-shell = { path = "../wp-shell" }

[lints]
workspace = true
