#![allow(dead_code)]

//! Which drawing belongs to which button.
//!
//! Generated by `tools/generate-icon-catalogue.sh` from `tools/icons.list`.
//! Do not edit: change the list and run the script again.
//!
//! The drawings are Fluent UI System Icons, which Microsoft publishes under the
//! MIT licence; `crates/wp-app/assets/icons/LICENSE.txt` is that licence. They
//! are built into the program rather than read at run time, so a copy of the
//! program is one file and needs nothing beside it.

/// What is drawn on a button.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[repr(usize)]
pub enum Icon {
    /// A button that carries no drawing at all.
    None = 0,
    Clipboard = 1,
    Scissors = 2,
    Copy = 3,
    Brush = 4,
    New = 5,
    Open = 6,
    Save = 7,
    Print = 8,
    Undo = 9,
    Redo = 10,
    Close = 11,
    Info = 12,
    Letter = 13,
    LetterUp = 14,
    LetterDown = 15,
    ChangeCase = 16,
    LetterClear = 17,
    Subscript = 18,
    Superscript = 19,
    TextEffects = 20,
    Highlight = 21,
    TextColor = 22,
    Bullets = 23,
    Numbering = 24,
    MultilevelList = 25,
    IndentMore = 26,
    IndentLess = 27,
    Sort = 28,
    Pilcrow = 29,
    AlignStart = 30,
    AlignCenter = 31,
    AlignEnd = 32,
    AlignBoth = 33,
    LineSpacing = 34,
    Shading = 35,
    Borders = 36,
    Find = 37,
    Replace = 38,
    Select = 39,
    CoverPage = 40,
    BlankPage = 41,
    PageBreak = 42,
    Table = 43,
    Picture = 44,
    Shapes = 45,
    SmartArt = 46,
    Chart = 47,
    Screenshot = 48,
    Video = 49,
    Link = 50,
    Bookmark = 51,
    CrossReference = 52,
    Comment = 53,
    NewComment = 54,
    DeleteComment = 55,
    ShowComments = 56,
    Header = 57,
    Footer = 58,
    PageNumber = 59,
    TextBox = 60,
    QuickParts = 61,
    WordArt = 62,
    DropCap = 63,
    Signature = 64,
    DateTime = 65,
    Object = 66,
    Equation = 67,
    Symbol = 68,
    Themes = 69,
    Colors = 70,
    Fonts = 71,
    ParagraphSpacing = 72,
    Effects = 73,
    SetAsDefault = 74,
    Watermark = 75,
    PageColor = 76,
    PageBorders = 77,
    Margins = 78,
    Orientation = 79,
    PageSize = 80,
    Columns = 81,
    Breaks = 82,
    LineNumbers = 83,
    Hyphenation = 84,
    Position = 85,
    WrapText = 86,
    BringForward = 87,
    SendBackward = 88,
    SelectionPane = 89,
    AlignObjects = 90,
    Group = 91,
    Rotate = 92,
    TableOfContents = 93,
    AddText = 94,
    UpdateTable = 95,
    Footnote = 96,
    Endnote = 97,
    NextFootnote = 98,
    ShowNotes = 99,
    Citation = 100,
    ManageSources = 101,
    Bibliography = 102,
    Caption = 103,
    TableOfFigures = 104,
    MarkEntry = 105,
    Index = 106,
    MarkCitation = 107,
    TableOfAuthorities = 108,
    Envelope = 109,
    Labels = 110,
    MailMerge = 111,
    Recipients = 112,
    EditRecipients = 113,
    MergeFields = 114,
    AddressBlock = 115,
    GreetingLine = 116,
    InsertMergeField = 117,
    Rules = 118,
    MatchFields = 119,
    UpdateLabels = 120,
    PreviewResults = 121,
    FindRecipient = 122,
    CheckErrors = 123,
    FinishMerge = 124,
    Spelling = 125,
    Thesaurus = 126,
    WordCount = 127,
    Accessibility = 128,
    Translate = 129,
    Language = 130,
    Previous = 131,
    Next = 132,
    ShowMarkup = 133,
    ReviewingPane = 134,
    TrackChanges = 135,
    Accept = 136,
    Reject = 137,
    Compare = 138,
    BlockAuthors = 139,
    RestrictEditing = 140,
    HideInk = 141,
    ReadMode = 142,
    PrintLayout = 143,
    WebLayout = 144,
    Outline = 145,
    Draft = 146,
    Theme = 147,
    ScrollVertical = 148,
    SideToSide = 149,
    Ruler = 150,
    Gridlines = 151,
    Zoom = 152,
    ZoomHundred = 153,
    OnePage = 154,
    MultiplePages = 155,
    PageWidth = 156,
    JoinPages = 157,
    NewWindow = 158,
    ArrangeAll = 159,
    Split = 160,
    SideBySide = 161,
    SynchronousScrolling = 162,
    ResetWindow = 163,
    Macros = 164,
    Properties = 165,
    Help = 166,
    Feedback = 167,
    Training = 168,
    WhatsNew = 169,
    InsertRowAbove = 170,
    InsertRowBelow = 171,
    InsertColumnLeft = 172,
    InsertColumnRight = 173,
    DeleteRow = 174,
    DeleteColumn = 175,
    DeleteTable = 176,
    MergeCells = 177,
    SplitCells = 178,
    TableProperties = 179,
    BorderNone = 180,
    BorderOutside = 181,
    BorderBottom = 182,
    BorderTop = 183,
    AutoFit = 184,
    CellAlign = 185,
    HeaderRow = 186,
    BandedRows = 187,
    /// The only icon here not from the Fluent set: it has no gear, and Word's
    /// Options needs one. Drawn the same way as the rest, as filled paths.
    Settings = 188,
}

/// How many there are, so the drawings can be kept in a flat array.
pub const COUNT: usize = 188;

/// Every icon, in the order the catalogue declares them.
///
/// The array position is the enum value, which is what lets a cache be
/// indexed by `icon as usize`.
pub static ALL: [Icon; COUNT] = [
    Icon::None,
    Icon::Clipboard,
    Icon::Scissors,
    Icon::Copy,
    Icon::Brush,
    Icon::New,
    Icon::Open,
    Icon::Save,
    Icon::Print,
    Icon::Undo,
    Icon::Redo,
    Icon::Close,
    Icon::Info,
    Icon::Letter,
    Icon::LetterUp,
    Icon::LetterDown,
    Icon::ChangeCase,
    Icon::LetterClear,
    Icon::Subscript,
    Icon::Superscript,
    Icon::TextEffects,
    Icon::Highlight,
    Icon::TextColor,
    Icon::Bullets,
    Icon::Numbering,
    Icon::MultilevelList,
    Icon::IndentMore,
    Icon::IndentLess,
    Icon::Sort,
    Icon::Pilcrow,
    Icon::AlignStart,
    Icon::AlignCenter,
    Icon::AlignEnd,
    Icon::AlignBoth,
    Icon::LineSpacing,
    Icon::Shading,
    Icon::Borders,
    Icon::Find,
    Icon::Replace,
    Icon::Select,
    Icon::CoverPage,
    Icon::BlankPage,
    Icon::PageBreak,
    Icon::Table,
    Icon::Picture,
    Icon::Shapes,
    Icon::SmartArt,
    Icon::Chart,
    Icon::Screenshot,
    Icon::Video,
    Icon::Link,
    Icon::Bookmark,
    Icon::CrossReference,
    Icon::Comment,
    Icon::NewComment,
    Icon::DeleteComment,
    Icon::ShowComments,
    Icon::Header,
    Icon::Footer,
    Icon::PageNumber,
    Icon::TextBox,
    Icon::QuickParts,
    Icon::WordArt,
    Icon::DropCap,
    Icon::Signature,
    Icon::DateTime,
    Icon::Object,
    Icon::Equation,
    Icon::Symbol,
    Icon::Themes,
    Icon::Colors,
    Icon::Fonts,
    Icon::ParagraphSpacing,
    Icon::Effects,
    Icon::SetAsDefault,
    Icon::Watermark,
    Icon::PageColor,
    Icon::PageBorders,
    Icon::Margins,
    Icon::Orientation,
    Icon::PageSize,
    Icon::Columns,
    Icon::Breaks,
    Icon::LineNumbers,
    Icon::Hyphenation,
    Icon::Position,
    Icon::WrapText,
    Icon::BringForward,
    Icon::SendBackward,
    Icon::SelectionPane,
    Icon::AlignObjects,
    Icon::Group,
    Icon::Rotate,
    Icon::TableOfContents,
    Icon::AddText,
    Icon::UpdateTable,
    Icon::Footnote,
    Icon::Endnote,
    Icon::NextFootnote,
    Icon::ShowNotes,
    Icon::Citation,
    Icon::ManageSources,
    Icon::Bibliography,
    Icon::Caption,
    Icon::TableOfFigures,
    Icon::MarkEntry,
    Icon::Index,
    Icon::MarkCitation,
    Icon::TableOfAuthorities,
    Icon::Envelope,
    Icon::Labels,
    Icon::MailMerge,
    Icon::Recipients,
    Icon::EditRecipients,
    Icon::MergeFields,
    Icon::AddressBlock,
    Icon::GreetingLine,
    Icon::InsertMergeField,
    Icon::Rules,
    Icon::MatchFields,
    Icon::UpdateLabels,
    Icon::PreviewResults,
    Icon::FindRecipient,
    Icon::CheckErrors,
    Icon::FinishMerge,
    Icon::Spelling,
    Icon::Thesaurus,
    Icon::WordCount,
    Icon::Accessibility,
    Icon::Translate,
    Icon::Language,
    Icon::Previous,
    Icon::Next,
    Icon::ShowMarkup,
    Icon::ReviewingPane,
    Icon::TrackChanges,
    Icon::Accept,
    Icon::Reject,
    Icon::Compare,
    Icon::BlockAuthors,
    Icon::RestrictEditing,
    Icon::HideInk,
    Icon::ReadMode,
    Icon::PrintLayout,
    Icon::WebLayout,
    Icon::Outline,
    Icon::Draft,
    Icon::Theme,
    Icon::ScrollVertical,
    Icon::SideToSide,
    Icon::Ruler,
    Icon::Gridlines,
    Icon::Zoom,
    Icon::ZoomHundred,
    Icon::OnePage,
    Icon::MultiplePages,
    Icon::PageWidth,
    Icon::JoinPages,
    Icon::NewWindow,
    Icon::ArrangeAll,
    Icon::Split,
    Icon::SideBySide,
    Icon::SynchronousScrolling,
    Icon::ResetWindow,
    Icon::Macros,
    Icon::Properties,
    Icon::Help,
    Icon::Feedback,
    Icon::Training,
    Icon::WhatsNew,
    Icon::InsertRowAbove,
    Icon::InsertRowBelow,
    Icon::InsertColumnLeft,
    Icon::InsertColumnRight,
    Icon::DeleteRow,
    Icon::DeleteColumn,
    Icon::DeleteTable,
    Icon::MergeCells,
    Icon::SplitCells,
    Icon::TableProperties,
    Icon::BorderNone,
    Icon::BorderOutside,
    Icon::BorderBottom,
    Icon::BorderTop,
    Icon::AutoFit,
    Icon::CellAlign,
    Icon::HeaderRow,
    Icon::BandedRows,
];

impl Icon {
    /// The file a drawing comes from, at the size asked for.
    ///
    /// Fluent draws each icon afresh at every size rather than scaling one, so
    /// the twenty-pixel art is used for the small buttons and the twenty-four
    /// pixel art, which carries more detail, for the large ones.
    #[must_use]
    pub fn source(self, large: bool) -> &'static str {
        match self {
            Self::None => "",
            Self::Clipboard => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_clipboard_paste_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_clipboard_paste_20_regular.svg")
                }
            }
            Self::Scissors => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_cut_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_cut_20_regular.svg")
                }
            }
            Self::Copy => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_copy_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_copy_20_regular.svg")
                }
            }
            Self::Brush => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_paint_brush_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_paint_brush_20_regular.svg")
                }
            }
            Self::New => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_document_add_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_document_add_20_regular.svg")
                }
            }
            Self::Open => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_folder_open_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_folder_open_20_regular.svg")
                }
            }
            Self::Save => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_save_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_save_20_regular.svg")
                }
            }
            Self::Print => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_print_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_print_20_regular.svg")
                }
            }
            Self::Undo => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_arrow_undo_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_arrow_undo_20_regular.svg")
                }
            }
            Self::Redo => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_arrow_redo_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_arrow_redo_20_regular.svg")
                }
            }
            Self::Close => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_dismiss_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_dismiss_20_regular.svg")
                }
            }
            Self::Settings => {
                if large {
                    include_str!("../../assets/icons/settings_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/settings_20_regular.svg")
                }
            }
            Self::Info => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_info_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_info_20_regular.svg")
                }
            }
            Self::Letter => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_text_font_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_text_font_20_regular.svg")
                }
            }
            Self::LetterUp => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_text_font_size_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_text_font_size_20_regular.svg")
                }
            }
            Self::LetterDown => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_text_font_size_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_text_font_size_20_regular.svg")
                }
            }
            Self::ChangeCase => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_text_case_title_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_text_case_title_20_regular.svg")
                }
            }
            Self::LetterClear => {
                if large {
                    include_str!(
                        "../../assets/icons/ic_fluent_text_clear_formatting_24_regular.svg"
                    )
                } else {
                    include_str!(
                        "../../assets/icons/ic_fluent_text_clear_formatting_20_regular.svg"
                    )
                }
            }
            Self::Subscript => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_text_subscript_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_text_subscript_20_regular.svg")
                }
            }
            Self::Superscript => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_text_superscript_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_text_superscript_20_regular.svg")
                }
            }
            Self::TextEffects => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_text_effects_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_text_effects_20_regular.svg")
                }
            }
            Self::Highlight => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_highlight_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_highlight_20_regular.svg")
                }
            }
            Self::TextColor => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_text_color_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_text_color_20_regular.svg")
                }
            }
            Self::Bullets => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_text_bullet_list_ltr_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_text_bullet_list_ltr_20_regular.svg")
                }
            }
            Self::Numbering => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_text_number_list_ltr_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_text_number_list_ltr_20_regular.svg")
                }
            }
            Self::MultilevelList => {
                if large {
                    include_str!(
                        "../../assets/icons/ic_fluent_text_bullet_list_tree_24_regular.svg"
                    )
                } else {
                    include_str!(
                        "../../assets/icons/ic_fluent_text_bullet_list_tree_20_regular.svg"
                    )
                }
            }
            Self::IndentMore => {
                if large {
                    include_str!(
                        "../../assets/icons/ic_fluent_text_indent_increase_ltr_24_regular.svg"
                    )
                } else {
                    include_str!(
                        "../../assets/icons/ic_fluent_text_indent_increase_ltr_20_regular.svg"
                    )
                }
            }
            Self::IndentLess => {
                if large {
                    include_str!(
                        "../../assets/icons/ic_fluent_text_indent_decrease_ltr_24_regular.svg"
                    )
                } else {
                    include_str!(
                        "../../assets/icons/ic_fluent_text_indent_decrease_ltr_20_regular.svg"
                    )
                }
            }
            Self::Sort => {
                if large {
                    include_str!(
                        "../../assets/icons/ic_fluent_arrow_sort_down_lines_24_regular.svg"
                    )
                } else {
                    include_str!(
                        "../../assets/icons/ic_fluent_arrow_sort_down_lines_20_regular.svg"
                    )
                }
            }
            Self::Pilcrow => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_text_paragraph_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_text_paragraph_20_regular.svg")
                }
            }
            Self::AlignStart => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_text_align_left_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_text_align_left_20_regular.svg")
                }
            }
            Self::AlignCenter => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_text_align_center_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_text_align_center_20_regular.svg")
                }
            }
            Self::AlignEnd => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_text_align_right_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_text_align_right_20_regular.svg")
                }
            }
            Self::AlignBoth => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_text_align_justify_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_text_align_justify_20_regular.svg")
                }
            }
            Self::LineSpacing => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_text_line_spacing_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_text_line_spacing_20_regular.svg")
                }
            }
            Self::Shading => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_color_fill_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_color_fill_20_regular.svg")
                }
            }
            Self::Borders => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_border_all_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_border_all_20_regular.svg")
                }
            }
            Self::Find => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_search_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_search_20_regular.svg")
                }
            }
            Self::Replace => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_text_grammar_wand_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_text_grammar_wand_20_regular.svg")
                }
            }
            Self::Select => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_cursor_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_cursor_20_regular.svg")
                }
            }
            Self::CoverPage => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_document_header_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_document_header_20_regular.svg")
                }
            }
            Self::BlankPage => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_document_one_page_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_document_one_page_20_regular.svg")
                }
            }
            Self::PageBreak => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_document_page_break_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_document_page_break_20_regular.svg")
                }
            }
            Self::Table => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_table_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_table_20_regular.svg")
                }
            }
            Self::Picture => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_image_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_image_20_regular.svg")
                }
            }
            Self::Shapes => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_shapes_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_shapes_20_regular.svg")
                }
            }
            Self::SmartArt => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_organization_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_organization_20_regular.svg")
                }
            }
            Self::Chart => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_data_bar_vertical_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_data_bar_vertical_20_regular.svg")
                }
            }
            Self::Screenshot => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_screenshot_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_screenshot_20_regular.svg")
                }
            }
            Self::Video => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_video_clip_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_video_clip_20_regular.svg")
                }
            }
            Self::Link => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_link_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_link_20_regular.svg")
                }
            }
            Self::Bookmark => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_bookmark_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_bookmark_20_regular.svg")
                }
            }
            Self::CrossReference => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_document_link_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_document_link_20_regular.svg")
                }
            }
            Self::Comment => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_comment_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_comment_20_regular.svg")
                }
            }
            Self::NewComment => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_comment_add_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_comment_add_20_regular.svg")
                }
            }
            Self::DeleteComment => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_comment_dismiss_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_comment_dismiss_20_regular.svg")
                }
            }
            Self::ShowComments => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_comment_multiple_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_comment_multiple_20_regular.svg")
                }
            }
            Self::Header => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_document_header_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_document_header_20_regular.svg")
                }
            }
            Self::Footer => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_document_footer_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_document_footer_20_regular.svg")
                }
            }
            Self::PageNumber => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_document_page_number_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_document_page_number_20_regular.svg")
                }
            }
            Self::TextBox => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_textbox_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_textbox_20_regular.svg")
                }
            }
            Self::QuickParts => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_text_field_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_text_field_20_regular.svg")
                }
            }
            Self::WordArt => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_text_effects_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_text_effects_20_regular.svg")
                }
            }
            Self::DropCap => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_text_first_line_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_text_first_line_20_regular.svg")
                }
            }
            Self::Signature => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_signature_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_signature_20_regular.svg")
                }
            }
            Self::DateTime => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_calendar_ltr_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_calendar_ltr_20_regular.svg")
                }
            }
            Self::Object => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_cube_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_cube_20_regular.svg")
                }
            }
            Self::Equation => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_math_formula_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_math_formula_20_regular.svg")
                }
            }
            Self::Symbol => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_symbols_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_symbols_20_regular.svg")
                }
            }
            Self::Themes => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_color_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_color_20_regular.svg")
                }
            }
            Self::Colors => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_color_background_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_color_background_20_regular.svg")
                }
            }
            Self::Fonts => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_text_font_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_text_font_20_regular.svg")
                }
            }
            Self::ParagraphSpacing => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_text_line_spacing_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_text_line_spacing_20_regular.svg")
                }
            }
            Self::Effects => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_sparkle_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_sparkle_20_regular.svg")
                }
            }
            Self::SetAsDefault => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_checkmark_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_checkmark_20_regular.svg")
                }
            }
            Self::Watermark => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_water_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_water_20_regular.svg")
                }
            }
            Self::PageColor => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_paint_bucket_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_paint_bucket_20_regular.svg")
                }
            }
            Self::PageBorders => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_border_outside_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_border_outside_20_regular.svg")
                }
            }
            Self::Margins => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_document_margins_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_document_margins_20_regular.svg")
                }
            }
            Self::Orientation => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_orientation_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_orientation_20_regular.svg")
                }
            }
            Self::PageSize => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_resize_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_resize_20_regular.svg")
                }
            }
            Self::Columns => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_column_triple_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_column_triple_20_regular.svg")
                }
            }
            Self::Breaks => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_document_page_break_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_document_page_break_20_regular.svg")
                }
            }
            Self::LineNumbers => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_text_number_format_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_text_number_format_20_regular.svg")
                }
            }
            Self::Hyphenation => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_subtract_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_subtract_20_regular.svg")
                }
            }
            Self::Position => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_position_to_front_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_position_to_front_20_regular.svg")
                }
            }
            Self::WrapText => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_text_wrap_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_text_wrap_20_regular.svg")
                }
            }
            Self::BringForward => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_position_forward_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_position_forward_20_regular.svg")
                }
            }
            Self::SendBackward => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_position_backward_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_position_backward_20_regular.svg")
                }
            }
            Self::SelectionPane => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_panel_left_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_panel_left_20_regular.svg")
                }
            }
            Self::AlignObjects => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_align_left_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_align_left_20_regular.svg")
                }
            }
            Self::Group => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_group_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_group_20_regular.svg")
                }
            }
            Self::Rotate => {
                if large {
                    include_str!(
                        "../../assets/icons/ic_fluent_arrow_rotate_clockwise_24_regular.svg"
                    )
                } else {
                    include_str!(
                        "../../assets/icons/ic_fluent_arrow_rotate_clockwise_20_regular.svg"
                    )
                }
            }
            Self::TableOfContents => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_document_bullet_list_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_document_bullet_list_20_regular.svg")
                }
            }
            Self::AddText => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_text_add_t_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_text_add_t_20_regular.svg")
                }
            }
            Self::UpdateTable => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_arrow_sync_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_arrow_sync_20_regular.svg")
                }
            }
            Self::Footnote => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_document_footer_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_document_footer_20_regular.svg")
                }
            }
            Self::Endnote => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_document_landscape_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_document_landscape_20_regular.svg")
                }
            }
            Self::NextFootnote => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_arrow_next_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_arrow_next_20_regular.svg")
                }
            }
            Self::ShowNotes => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_note_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_note_20_regular.svg")
                }
            }
            Self::Citation => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_book_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_book_20_regular.svg")
                }
            }
            Self::ManageSources => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_book_open_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_book_open_20_regular.svg")
                }
            }
            Self::Bibliography => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_book_information_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_book_information_20_regular.svg")
                }
            }
            Self::Caption => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_image_alt_text_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_image_alt_text_20_regular.svg")
                }
            }
            Self::TableOfFigures => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_document_table_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_document_table_20_regular.svg")
                }
            }
            Self::MarkEntry => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_bookmark_add_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_bookmark_add_20_regular.svg")
                }
            }
            Self::Index => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_apps_list_detail_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_apps_list_detail_20_regular.svg")
                }
            }
            Self::MarkCitation => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_book_add_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_book_add_20_regular.svg")
                }
            }
            Self::TableOfAuthorities => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_book_toolbox_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_book_toolbox_20_regular.svg")
                }
            }
            Self::Envelope => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_mail_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_mail_20_regular.svg")
                }
            }
            Self::Labels => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_tag_multiple_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_tag_multiple_20_regular.svg")
                }
            }
            Self::MailMerge => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_mail_template_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_mail_template_20_regular.svg")
                }
            }
            Self::Recipients => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_people_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_people_20_regular.svg")
                }
            }
            Self::EditRecipients => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_people_edit_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_people_edit_20_regular.svg")
                }
            }
            Self::MergeFields => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_highlight_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_highlight_20_regular.svg")
                }
            }
            Self::AddressBlock => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_mail_read_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_mail_read_20_regular.svg")
                }
            }
            Self::GreetingLine => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_person_note_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_person_note_20_regular.svg")
                }
            }
            Self::InsertMergeField => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_text_field_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_text_field_20_regular.svg")
                }
            }
            Self::Rules => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_branch_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_branch_20_regular.svg")
                }
            }
            Self::MatchFields => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_arrow_swap_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_arrow_swap_20_regular.svg")
                }
            }
            Self::UpdateLabels => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_arrow_sync_circle_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_arrow_sync_circle_20_regular.svg")
                }
            }
            Self::PreviewResults => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_eye_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_eye_20_regular.svg")
                }
            }
            Self::FindRecipient => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_person_search_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_person_search_20_regular.svg")
                }
            }
            Self::CheckErrors => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_error_circle_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_error_circle_20_regular.svg")
                }
            }
            Self::FinishMerge => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_mail_checkmark_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_mail_checkmark_20_regular.svg")
                }
            }
            Self::Spelling => {
                if large {
                    include_str!(
                        "../../assets/icons/ic_fluent_text_grammar_checkmark_24_regular.svg"
                    )
                } else {
                    include_str!(
                        "../../assets/icons/ic_fluent_text_grammar_checkmark_20_regular.svg"
                    )
                }
            }
            Self::Thesaurus => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_book_letter_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_book_letter_20_regular.svg")
                }
            }
            Self::WordCount => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_text_number_list_ltr_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_text_number_list_ltr_20_regular.svg")
                }
            }
            Self::Accessibility => {
                if large {
                    include_str!(
                        "../../assets/icons/ic_fluent_accessibility_checkmark_24_regular.svg"
                    )
                } else {
                    include_str!(
                        "../../assets/icons/ic_fluent_accessibility_checkmark_20_regular.svg"
                    )
                }
            }
            Self::Translate => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_translate_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_translate_20_regular.svg")
                }
            }
            Self::Language => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_local_language_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_local_language_20_regular.svg")
                }
            }
            Self::Previous => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_arrow_previous_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_arrow_previous_20_regular.svg")
                }
            }
            Self::Next => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_arrow_next_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_arrow_next_20_regular.svg")
                }
            }
            Self::ShowMarkup => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_edit_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_edit_20_regular.svg")
                }
            }
            Self::ReviewingPane => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_panel_right_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_panel_right_20_regular.svg")
                }
            }
            Self::TrackChanges => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_text_edit_style_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_text_edit_style_20_regular.svg")
                }
            }
            Self::Accept => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_checkmark_circle_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_checkmark_circle_20_regular.svg")
                }
            }
            Self::Reject => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_dismiss_circle_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_dismiss_circle_20_regular.svg")
                }
            }
            Self::Compare => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_document_multiple_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_document_multiple_20_regular.svg")
                }
            }
            Self::BlockAuthors => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_person_prohibited_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_person_prohibited_20_regular.svg")
                }
            }
            Self::RestrictEditing => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_lock_closed_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_lock_closed_20_regular.svg")
                }
            }
            Self::HideInk => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_ink_stroke_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_ink_stroke_20_regular.svg")
                }
            }
            Self::ReadMode => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_book_open_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_book_open_20_regular.svg")
                }
            }
            Self::PrintLayout => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_document_one_page_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_document_one_page_20_regular.svg")
                }
            }
            Self::WebLayout => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_globe_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_globe_20_regular.svg")
                }
            }
            Self::Outline => {
                if large {
                    include_str!(
                        "../../assets/icons/ic_fluent_text_bullet_list_tree_24_regular.svg"
                    )
                } else {
                    include_str!(
                        "../../assets/icons/ic_fluent_text_bullet_list_tree_20_regular.svg"
                    )
                }
            }
            Self::Draft => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_document_text_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_document_text_20_regular.svg")
                }
            }
            Self::Theme => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_weather_moon_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_weather_moon_20_regular.svg")
                }
            }
            Self::ScrollVertical => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_arrow_autofit_height_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_arrow_autofit_height_20_regular.svg")
                }
            }
            Self::SideToSide => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_arrow_autofit_width_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_arrow_autofit_width_20_regular.svg")
                }
            }
            Self::Ruler => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_ruler_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_ruler_20_regular.svg")
                }
            }
            Self::Gridlines => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_grid_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_grid_20_regular.svg")
                }
            }
            Self::Zoom => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_zoom_in_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_zoom_in_20_regular.svg")
                }
            }
            Self::ZoomHundred => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_document_width_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_document_width_20_regular.svg")
                }
            }
            Self::OnePage => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_document_one_page_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_document_one_page_20_regular.svg")
                }
            }
            Self::MultiplePages => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_document_multiple_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_document_multiple_20_regular.svg")
                }
            }
            Self::PageWidth => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_arrow_autofit_width_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_arrow_autofit_width_20_regular.svg")
                }
            }
            Self::JoinPages => {
                if large {
                    include_str!(
                        "../../assets/icons/ic_fluent_arrow_minimize_vertical_24_regular.svg"
                    )
                } else {
                    include_str!(
                        "../../assets/icons/ic_fluent_arrow_minimize_vertical_20_regular.svg"
                    )
                }
            }
            Self::NewWindow => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_window_new_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_window_new_20_regular.svg")
                }
            }
            Self::ArrangeAll => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_window_multiple_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_window_multiple_20_regular.svg")
                }
            }
            Self::Split => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_split_horizontal_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_split_horizontal_20_regular.svg")
                }
            }
            Self::SideBySide => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_dual_screen_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_dual_screen_20_regular.svg")
                }
            }
            Self::SynchronousScrolling => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_arrow_sync_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_arrow_sync_20_regular.svg")
                }
            }
            Self::ResetWindow => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_window_arrow_up_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_window_arrow_up_20_regular.svg")
                }
            }
            Self::Macros => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_code_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_code_20_regular.svg")
                }
            }
            Self::Properties => {
                if large {
                    include_str!(
                        "../../assets/icons/ic_fluent_document_bullet_list_clock_24_regular.svg"
                    )
                } else {
                    include_str!(
                        "../../assets/icons/ic_fluent_document_bullet_list_clock_20_regular.svg"
                    )
                }
            }
            Self::Help => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_question_circle_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_question_circle_20_regular.svg")
                }
            }
            Self::Feedback => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_person_feedback_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_person_feedback_20_regular.svg")
                }
            }
            Self::Training => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_hat_graduation_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_hat_graduation_20_regular.svg")
                }
            }
            Self::WhatsNew => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_star_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_star_20_regular.svg")
                }
            }
            Self::InsertRowAbove => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_table_stack_above_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_table_stack_above_20_regular.svg")
                }
            }
            Self::InsertRowBelow => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_table_stack_below_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_table_stack_below_20_regular.svg")
                }
            }
            Self::InsertColumnLeft => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_table_stack_left_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_table_stack_left_20_regular.svg")
                }
            }
            Self::InsertColumnRight => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_table_stack_right_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_table_stack_right_20_regular.svg")
                }
            }
            Self::DeleteRow => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_table_delete_row_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_table_delete_row_20_regular.svg")
                }
            }
            Self::DeleteColumn => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_table_delete_column_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_table_delete_column_20_regular.svg")
                }
            }
            Self::DeleteTable => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_table_dismiss_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_table_dismiss_20_regular.svg")
                }
            }
            Self::MergeCells => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_table_cells_merge_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_table_cells_merge_20_regular.svg")
                }
            }
            Self::SplitCells => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_table_cells_split_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_table_cells_split_20_regular.svg")
                }
            }
            Self::TableProperties => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_table_settings_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_table_settings_20_regular.svg")
                }
            }
            Self::BorderNone => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_border_none_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_border_none_20_regular.svg")
                }
            }
            Self::BorderOutside => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_border_outside_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_border_outside_20_regular.svg")
                }
            }
            Self::BorderBottom => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_border_bottom_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_border_bottom_20_regular.svg")
                }
            }
            Self::BorderTop => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_border_top_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_border_top_20_regular.svg")
                }
            }
            Self::AutoFit => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_arrow_autofit_width_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_arrow_autofit_width_20_regular.svg")
                }
            }
            Self::CellAlign => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_table_cell_center_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_table_cell_center_20_regular.svg")
                }
            }
            Self::HeaderRow => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_table_freeze_row_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_table_freeze_row_20_regular.svg")
                }
            }
            Self::BandedRows => {
                if large {
                    include_str!("../../assets/icons/ic_fluent_table_simple_24_regular.svg")
                } else {
                    include_str!("../../assets/icons/ic_fluent_table_simple_20_regular.svg")
                }
            }
        }
    }
}
