#!/usr/bin/env bash
# Regenerates the code page tables the plain text reader decodes with.
#
# Why: a code page is a table of a hundred and twenty-eight characters, and a
# table typed by hand is a table with a typo in it somewhere - one that would
# turn one letter of somebody's text into another and never be noticed. These
# are generated from the mappings Python carries, which are Unicode's own
# published mapping files compiled in, and the result is committed, so that
# the program still builds from its own source alone.
#
# Where the data comes from: the build image carries Python for its own
# reasons, and Python's codec registry holds every code page this program
# names. Nothing is downloaded and nothing is installed.
#
# Run: docker compose run --rm dev bash tools/generate-codepages.sh
#
# Afterwards: cargo fmt --all.

set -euo pipefail

ROOT=$(cd "$(dirname "$0")/.." && pwd)
OUT="$ROOT/crates/wp-text/src/tables.rs"

python3 - "$OUT" <<'PYTHON'
import sys

# Each code page: the name this program uses for it, and Python's name for it.
PAGES = [
    ("WINDOWS_1250", "cp1250"),
    ("WINDOWS_1251", "cp1251"),
    ("WINDOWS_1252", "cp1252"),
    ("WINDOWS_1253", "cp1253"),
    ("WINDOWS_1254", "cp1254"),
    ("WINDOWS_1255", "cp1255"),
    ("WINDOWS_1256", "cp1256"),
    ("WINDOWS_1257", "cp1257"),
    ("WINDOWS_1258", "cp1258"),
    ("ISO_8859_1", "iso8859_1"),
    ("ISO_8859_2", "iso8859_2"),
    ("ISO_8859_5", "iso8859_5"),
    ("ISO_8859_7", "iso8859_7"),
    ("ISO_8859_9", "iso8859_9"),
    ("ISO_8859_15", "iso8859_15"),
    ("KOI8_R", "koi8_r"),
    ("KOI8_U", "koi8_u"),
    ("DOS_437", "cp437"),
    ("DOS_850", "cp850"),
    ("DOS_852", "cp852"),
    ("DOS_857", "cp857"),
    ("DOS_866", "cp866"),
]

out = []
out.append("//! The upper halves of the single-byte code pages.")
out.append("//!")
out.append("//! Generated by `tools/generate-codepages.sh` from the mapping tables Python")
out.append("//! carries. Do not edit: run the script again.")
out.append("//!")
out.append("//! Each table maps the bytes `0x80` to `0xFF` to characters; the lower half")
out.append("//! of every one of these code pages is ASCII. A byte the code page leaves")
out.append("//! undefined maps to the control character of the same value, which is what")
out.append("//! Windows makes of it.")
out.append("")
for name, codec in PAGES:
    table = []
    for byte in range(0x80, 0x100):
        try:
            character = bytes([byte]).decode(codec)
        except UnicodeDecodeError:
            character = chr(byte)
        if len(character) != 1:
            raise SystemExit(f"{codec}: byte {byte:#x} is not one character")
        table.append(f"'\\u{{{ord(character):04X}}}'")
    out.append(f"pub const {name}: [char; 128] = [")
    for start in range(0, 128, 8):
        out.append("    " + ", ".join(table[start:start + 8]) + ",")
    out.append("];")
    out.append("")

with open(sys.argv[1], "w", encoding="utf-8", newline="\n") as file:
    file.write("\n".join(out))
PYTHON

echo "wrote $OUT"

# The East Asian code pages: a byte past ASCII is a character of its own or
# the first of two, and the pairs number in the thousands. Each page is a
# table of its single bytes, the row of pairs each lead byte begins, and the
# rows, a character for every second byte from 0x40 to 0xFE — nought where
# the pair means nothing.
CJK="$ROOT/crates/wp-text/src/cjk_tables.rs"

python3 - "$CJK" <<'PYTHON'
import sys

PAGES = [
    ("CP932", "cp932"),
    ("CP936", "cp936"),
    ("CP949", "cp949"),
    ("CP950", "cp950"),
]

# Where Windows' own table has a character Python's has not: code page 936
# has the euro at 0x80, which Unicode's published CP936.TXT carries too.
EXTRA_SINGLE = {("cp936", 0x80): 0x20AC}

TRAILS = range(0x40, 0xFF)

out = []
out.append("//! The East Asian code pages: Shift-JIS (932), GBK (936), Unified Hangul")
out.append("//! (949) and Big5 (950).")
out.append("//!")
out.append("//! Generated by `tools/generate-codepages.sh` from the mapping tables Python")
out.append("//! carries. Do not edit: run the script again.")
out.append("//!")
out.append("//! For each: the characters of the single bytes `0x80` to `0xFF`, nought")
out.append("//! where the byte is not a character by itself; the row of pairs each of")
out.append("//! those bytes begins, `0xFF` where it begins none; and the rows, the")
out.append("//! character of each second byte from `0x40` to `0xFE`, nought where the")
out.append("//! pair means nothing. Every character is in the Basic Multilingual Plane.")
out.append("")
for name, codec in PAGES:
    single = []
    rows = []
    pairs = []
    for byte in range(0x80, 0x100):
        value = EXTRA_SINGLE.get((codec, byte), 0)
        try:
            character = bytes([byte]).decode(codec)
            if len(character) == 1:
                value = ord(character)
        except UnicodeDecodeError:
            pass
        single.append(value)
        row = []
        for trail in TRAILS:
            try:
                character = bytes([byte, trail]).decode(codec)
            except UnicodeDecodeError:
                row.append(0)
                continue
            if len(character) != 1 or ord(character) > 0xFFFF:
                row.append(0)
            else:
                row.append(ord(character))
        if value == 0 and any(row):
            rows.append(len(pairs) // len(TRAILS))
            pairs.extend(row)
        else:
            rows.append(0xFF)
    out.append(f"pub const {name}_SINGLE: [u16; 128] = [")
    for start in range(0, 128, 8):
        out.append("    " + ", ".join(f"0x{v:04X}" for v in single[start:start + 8]) + ",")
    out.append("];")
    out.append("")
    out.append(f"pub const {name}_ROWS: [u8; 128] = [")
    for start in range(0, 128, 16):
        out.append("    " + ", ".join(f"{v}" for v in rows[start:start + 16]) + ",")
    out.append("];")
    out.append("")
    out.append(f"pub static {name}_PAIRS: [u16; {len(pairs)}] = [")
    for start in range(0, len(pairs), 12):
        out.append("    " + ", ".join(f"0x{v:04X}" for v in pairs[start:start + 12]) + ",")
    out.append("];")
    out.append("")
    # A character with more than one code is written with the one Windows
    # writes it with, as Python's encoder does.
    codes = {}
    for byte in range(0x80, 0x100):
        if single[byte - 0x80]:
            codes.setdefault(single[byte - 0x80], []).append(byte)
        row = rows[byte - 0x80]
        if row != 0xFF:
            for index, trail in enumerate(TRAILS):
                value = pairs[row * len(TRAILS) + index]
                if value:
                    codes.setdefault(value, []).append(byte << 8 | trail)
    preferred = []
    for value, found in sorted(codes.items()):
        if len(found) < 2:
            continue
        try:
            written = chr(value).encode(codec)
        except UnicodeEncodeError:
            continue
        preferred.append((value, int.from_bytes(written, "big")))
    out.append(f"pub const {name}_PREFERRED: [(u16, u16); {len(preferred)}] = [")
    for value, code in preferred:
        out.append(f"    (0x{value:04X}, 0x{code:04X}),")
    out.append("];")
    out.append("")

with open(sys.argv[1], "w", encoding="utf-8", newline="\n") as file:
    file.write("\n".join(out))
PYTHON

echo "wrote $CJK"
