#!/usr/bin/env bash
# Writes the list of button drawings into Rust.
#
# A drawing is a file, and a file has to be named by a literal to be built into
# the program. That literal list is what this generates, so that tools/icons.list
# stays the one place a button's drawing is chosen.
#
# Run after changing tools/icons.list or re-running tools/fetch-icons.sh.
set -euo pipefail
cd "$(dirname "$0")/.."

list=tools/icons.list
out=crates/wp-app/src/chrome/icon_catalogue.rs
variants=$(grep -v '^#' "$list" | awk 'NF { print $1 }')
count=$(( $(printf '%s\n' "$variants" | wc -l) + 1 ))

{
  cat <<'HEADER'
#![allow(dead_code)]

//! Which drawing belongs to which button.
//!
//! Generated by `tools/generate-icon-catalogue.sh` from `tools/icons.list`.
//! Do not edit: change the list and run the script again.
//!
//! The drawings are Fluent UI System Icons, which Microsoft publishes under the
//! MIT licence; `crates/wp-app/assets/icons/LICENSE.txt` is that licence. They
//! are built into the program rather than read at run time, so a copy of the
//! program is one file and needs nothing beside it.

/// What is drawn on a button.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[repr(usize)]
pub enum Icon {
    /// A button that carries no drawing at all.
    None = 0,
HEADER

  printf '%s\n' "$variants" | awk '{ printf "    %s = %d,\n", $1, NR }'

  printf '}\n\n'
  printf '/// How many there are, so the drawings can be kept in a flat array.\n'
  printf 'pub const COUNT: usize = %d;\n\n' "$count"

  printf '/// Every icon, in the order the catalogue declares them.\n'
  printf '///\n'
  printf '/// The array position is the enum value, which is what lets a cache be\n'
  printf '/// indexed by `icon as usize`.\n'
  printf 'pub static ALL: [Icon; COUNT] = [\n'
  printf '    Icon::None,\n'
  printf '%s\n' "$variants" | awk '{ printf "    Icon::%s,\n", $1 }'
  printf '];\n'

  cat <<'BODY'

impl Icon {
    /// The file a drawing comes from, at the size asked for.
    ///
    /// Fluent draws each icon afresh at every size rather than scaling one, so
    /// the twenty-pixel art is used for the small buttons and the twenty-four
    /// pixel art, which carries more detail, for the large ones.
    #[must_use]
    pub fn source(self, large: bool) -> &'static str {
        match self {
            Self::None => "",
BODY

  grep -v '^#' "$list" | awk 'NF {
    printf "            Self::%s => {\n", $1
    printf "                if large {\n"
    printf "                    include_str!(\"../../assets/icons/ic_fluent_%s_24_regular.svg\")\n", $2
    printf "                } else {\n"
    printf "                    include_str!(\"../../assets/icons/ic_fluent_%s_20_regular.svg\")\n", $2
    printf "                }\n"
    printf "            }\n"
  }'

  cat <<'FOOTER'
        }
    }
}
FOOTER
} > "$out"

echo "wrote $out with $count icons"
