#!/usr/bin/env bash
# Regenerates the code page tables the plain text reader decodes with.
#
# Why: a code page is a table of a hundred and twenty-eight characters, and a
# table typed by hand is a table with a typo in it somewhere - one that would
# turn one letter of somebody's text into another and never be noticed. These
# are generated from the mappings Python carries, which are Unicode's own
# published mapping files compiled in, and the result is committed, so that
# the program still builds from its own source alone.
#
# Where the data comes from: the build image carries Python for its own
# reasons, and Python's codec registry holds every code page this program
# names. Nothing is downloaded and nothing is installed.
#
# Run: docker compose run --rm dev bash tools/generate-codepages.sh
#
# Afterwards: cargo fmt --all.

set -euo pipefail

ROOT=$(cd "$(dirname "$0")/.." && pwd)
OUT="$ROOT/crates/wp-text/src/tables.rs"

python3 - "$OUT" <<'PYTHON'
import sys

# Each code page: the name this program uses for it, and Python's name for it.
PAGES = [
    ("WINDOWS_1250", "cp1250"),
    ("WINDOWS_1251", "cp1251"),
    ("WINDOWS_1252", "cp1252"),
    ("WINDOWS_1253", "cp1253"),
    ("WINDOWS_1254", "cp1254"),
    ("WINDOWS_1255", "cp1255"),
    ("WINDOWS_1256", "cp1256"),
    ("WINDOWS_1257", "cp1257"),
    ("WINDOWS_1258", "cp1258"),
    ("ISO_8859_1", "iso8859_1"),
    ("ISO_8859_2", "iso8859_2"),
    ("ISO_8859_5", "iso8859_5"),
    ("ISO_8859_7", "iso8859_7"),
    ("ISO_8859_9", "iso8859_9"),
    ("ISO_8859_15", "iso8859_15"),
    ("KOI8_R", "koi8_r"),
    ("KOI8_U", "koi8_u"),
    ("DOS_437", "cp437"),
    ("DOS_850", "cp850"),
    ("DOS_852", "cp852"),
    ("DOS_857", "cp857"),
    ("DOS_866", "cp866"),
]

out = []
out.append("//! The upper halves of the single-byte code pages.")
out.append("//!")
out.append("//! Generated by `tools/generate-codepages.sh` from the mapping tables Python")
out.append("//! carries. Do not edit: run the script again.")
out.append("//!")
out.append("//! Each table maps the bytes `0x80` to `0xFF` to characters; the lower half")
out.append("//! of every one of these code pages is ASCII. A byte the code page leaves")
out.append("//! undefined maps to the control character of the same value, which is what")
out.append("//! Windows makes of it.")
out.append("")
for name, codec in PAGES:
    table = []
    for byte in range(0x80, 0x100):
        try:
            character = bytes([byte]).decode(codec)
        except UnicodeDecodeError:
            character = chr(byte)
        if len(character) != 1:
            raise SystemExit(f"{codec}: byte {byte:#x} is not one character")
        table.append(f"'\\u{{{ord(character):04X}}}'")
    out.append(f"pub const {name}: [char; 128] = [")
    for start in range(0, 128, 8):
        out.append("    " + ", ".join(table[start:start + 8]) + ",")
    out.append("];")
    out.append("")

with open(sys.argv[1], "w", encoding="utf-8", newline="\n") as file:
    file.write("\n".join(out))
PYTHON

echo "wrote $OUT"
